##############################################################
# Copyright 2023 Lawrence Livermore National Security, LLC
# (c.f. AUTHORS, NOTICE.LLNS, COPYING)
#
# This file is part of the Flux resource manager framework.
# For details, see https://github.com/flux-framework.
#
# SPDX-License-Identifier: LGPL-3.0
##############################################################

include:
  - local: '.gitlab/builds.gitlab-ci.yml'
  - local: '.gitlab/tests.gitlab-ci.yml'

stages:
  - build
  - test

default:
    retry: 1

## Job Specifications
corona-core-build:
    extends: 
        - .build-core
        - .corona
    stage: build

corona-core-test:
    needs: ["corona-core-build"]
    extends: 
        - .test-core
        - .corona
    stage: test

poodle-core-build:
    extends: 
        - .build-core
        - .poodle
    stage: build

poodle-core-test:
    needs: ["poodle-core-build"]
    extends: 
        - .test-core
        - .poodle
    stage: test

tioga-core-build:
    extends: 
        - .build-core
        - .tioga
    stage: build

tioga-core-test:
    needs: ["tioga-core-build"]
    extends: 
        - .test-core
        - .tioga
    stage: test

quartz-core-build:
    extends: 
        - .build-core
        - .quartz
    stage: build

quartz-core-test:
    needs: ["quartz-core-build"]
    extends: 
        - .test-core
        - .quartz
    stage: test

corona-pmix-test:
    needs: ["corona-core-build"]
    extends:
        - .test-pmix
        - .corona
    stage: test

corona-mpi-test:
    needs: ["corona-core-build", "corona-pmix-test"]
    extends:
        - .test-core-mpi
        - .corona
    variables:
        LLNL_FLUX_SCHEDULER_PARAMETERS: "-N 2 -q pdebug"
    stage: test
