##############################################################
# Copyright 2023 Lawrence Livermore National Security, LLC
# (c.f. AUTHORS, NOTICE.LLNS, COPYING)
#
# This file is part of the Flux resource manager framework.
# For details, see https://github.com/flux-framework.
#
# SPDX-License-Identifier: LGPL-3.0
##############################################################

.build-core:
  script:
    - git clone https://github.com/flux-framework/flux-core
    - cd flux-core
    - ./autogen.sh
    - mkdir build
    - cd build
    - mkdir install
    - ../configure --prefix=$(pwd)/install
    - make -j $(nproc)
    - make -j $(nproc) install
    - export CORE_BUILD_DIR=$(pwd)
    - export CORE_INSTALL_PREFIX=$(pwd)/install
    