##############################################################
# Copyright 2023 Lawrence Livermore National Security, LLC
# (c.f. AUTHORS, NOTICE.LLNS, COPYING)
#
# This file is part of the Flux resource manager framework.
# For details, see https://github.com/flux-framework.
#
# SPDX-License-Identifier: LGPL-3.0
##############################################################

.build-core:
    extends: .lc-variables
    variables:
        PYTHON: "/usr/bin/python3"
    script:
        - test -n ${CI_PIPELINE_ID}
        - export FTC_DIRECTORY=$(pwd)
        - mkdir /usr/WS1/${USER}/cibuilds/${CI_PIPELINE_ID}_${LCSCHEDCLUSTER}
        - export CI_DIRECTORY=/usr/WS1/${USER}/cibuilds/${CI_PIPELINE_ID}_${LCSCHEDCLUSTER}
        - cd ${CI_DIRECTORY}
        - git clone https://github.com/flux-framework/flux-core
        - cd flux-core
        - ./autogen.sh
        - mkdir build
        - mkdir install
        - cd build
        - ../configure --prefix=${CI_DIRECTORY}/flux-core/install
        - make -j $(nproc)
        ## need to install to get pkgconfig files
        - make -j $(nproc) install
        - export CORE_BUILD_DIR=$(pwd)
        - export CORE_INSTALL_PREFIX=${CI_DIRECTORY}/flux-core/install
        - cd $FTC_DIRECTORY
        - echo "CI_DIRECTORY=${CI_DIRECTORY}" >> build.env
        - echo "CORE_BUILD_DIR=${CORE_BUILD_DIR}" >> build.env
        - echo "CORE_INSTALL_PREFIX=${CORE_INSTALL_PREFIX}" >> build.env
    ## Save the exported directory names so later jobs can use the binaries that have already been built
    ## send these dirnames to tests as a .env file
    artifacts:
        reports:
            dotenv:
                - build.env
